plugins {
    id("com.android.application")
    id("kotlin-android")
    id("kotlin-kapt")
    id("com.google.devtools.ksp")
    id("androidx.navigation.safeargs.kotlin")
    id("com.google.gms.google-services")
    id("com.google.firebase.crashlytics")
}

android {
    compileSdk 34

    defaultConfig {
        applicationId "ceui.lisa.slinky"
        minSdk 23
        targetSdk 34

        def gitVersionCode = 'git rev-list HEAD --count'.execute().text.trim()
        versionCode Integer.parseInt(gitVersionCode)
        versionName "0.1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        dataBinding true
        viewBinding true
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    namespace 'ceui.lisa.slinky'
}



dependencies {

    implementation(project(":annotations")) // 1
    implementation(project(":processor"))
    kapt(project(":processor")) // 3

    implementation 'androidx.core:core-ktx:1.13.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.browser:browser:1.8.0'

    def retrofitVersion = "2.9.0"
    implementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
    implementation "com.squareup.retrofit2:converter-gson:$retrofitVersion"


    implementation 'com.tencent:mmkv-static:1.2.12'

    def kotlinx_coroutines_version = "1.8.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$kotlinx_coroutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinx_coroutines_version"
    implementation 'com.google.code.gson:gson:2.10.1'

    def glide_version = "4.16.0"
    implementation "com.github.bumptech.glide:glide:$glide_version"
    implementation "com.github.bumptech.glide:okhttp3-integration:$glide_version"
    kapt "com.github.bumptech.glide:compiler:$glide_version"


    def nav_version = "2.7.7"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'com.blankj:utilcodex:1.31.1'


    def room_version = "2.6.1"

    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"

    // ViewModel
    def lifecycle_version = "2.7.0"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"


    implementation "com.github.Justson.AgentWeb:agentweb-core:v4.1.9-androidx"


    implementation 'com.google.android.flexbox:flexbox:3.0.0'

    implementation platform('com.google.firebase:firebase-bom:32.7.4')
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'

    implementation 'com.github.yalantis:ucrop:2.2.6'

    implementation("io.github.panpf.zoomimage:zoomimage-view-sketch:1.0.2")

    implementation 'com.github.franmontiel:PersistentCookieJar:v1.0.1'
    implementation 'jp.wasabeef:glide-transformations:4.3.0'

    implementation 'com.gitee.zackratos:UltimateBarX:0.8.1'

    implementation 'com.airbnb.android:lottie:4.2.2'

    implementation 'com.github.duanhong169:drawabletoolbox:1.0.7'

    implementation 'com.jakewharton.timber:timber:5.0.1'


    def refresh_layout_version = "2.0.6"
    implementation  "io.github.scwang90:refresh-layout-kernel:$refresh_layout_version"     //核心必须依赖
    implementation  "io.github.scwang90:refresh-header-classics:$refresh_layout_version"    //经典刷新头
    implementation  "io.github.scwang90:refresh-header-radar:$refresh_layout_version"       //雷达刷新头
    implementation  "io.github.scwang90:refresh-header-falsify:$refresh_layout_version"     //虚拟刷新头
    implementation  "io.github.scwang90:refresh-header-material:$refresh_layout_version"    //谷歌刷新头
    implementation  "io.github.scwang90:refresh-header-two-level:$refresh_layout_version"   //二级刷新头
    implementation  "io.github.scwang90:refresh-footer-ball:$refresh_layout_version"        //球脉冲加载
    implementation  "io.github.scwang90:refresh-footer-classics:$refresh_layout_version"    //经典加载
//    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.10'


    implementation 'com.github.KuangGang:RoundCorners:2.0.0'

    def anyLayerVersion = "1.0.7"
    implementation "com.github.goweii:Layer:$anyLayerVersion"

    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}