package ceui.lisa.slinky.core

import android.view.ViewGroup
import androidx.databinding.ViewDataBinding
import androidx.lifecycle.LifecycleOwner
import androidx.recyclerview.widget.ListAdapter
import ceui.lisa.slinky.ui.SlinkyItem
import ceui.lisa.slinky.ui.SlinkyViewHolder
import ceui.lisa.slinky.viewholdermap.ViewHolderFactory

class SLAdapter(
    private val lifecycleOwner: LifecycleOwner,
) : ListAdapter<SlinkyItem, SlinkyViewHolder<ViewDataBinding, SlinkyItem>>(AdapterDiffer) {

    override fun onCreateViewHolder(
        parent: ViewGroup, viewType: Int
    ): SlinkyViewHolder<ViewDataBinding, SlinkyItem> {
        val autoGeneratedViewHolderBuilder = ViewHolderFactory.VIEW_HOLDER_MAP[viewType]
            ?: throw RuntimeException("itemHolder should add @ItemHolder")
        return autoGeneratedViewHolderBuilder(parent).bindLifecycleOwner(lifecycleOwner) as SlinkyViewHolder<ViewDataBinding, SlinkyItem>
    }

    override fun onBindViewHolder(
        holder: SlinkyViewHolder<ViewDataBinding, SlinkyItem>, position: Int
    ) {
        val item = getItem(position)
        holder.lifecycleOwnerBindView(item)
    }

    override fun getItemViewType(position: Int): Int {
        return getItem(position).getItemViewType()
    }

    override fun getItemId(position: Int): Long {
        return getItem(position).getItemId()
    }
}